# Generated by Django 5.2.9 on 2025-12-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('home_inline_1', 'Home (Inline)'), ('dashboard_inline_1', 'Dashboard (Inline)')], max_length=64)),
                ('headline', models.CharField(max_length=80)),
                ('body', models.CharField(blank=True, max_length=140)),
                ('target_url', models.URLField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower is shown first.')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['placement', 'priority', '-created_at'],
            },
        ),
    ]
