# Generated by Django 5.2.9 on 2025-12-24

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("directory", "0002_alter_serviceprovider_country"),
	]

	operations = [
		migrations.CreateModel(
			name="ProviderSettings",
			fields=[
				("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
				(
					"provider_backend",
					models.CharField(
						choices=[("OSM", "OpenStreetMap"), ("GOOGLE", "Google Places")],
						default="OSM",
						help_text="Select which provider source powers external results.",
						max_length=16,
					),
				),
				(
					"google_maps_api_key",
					models.CharField(
						blank=True,
						help_text="Optional. If set, overrides GOOGLE_MAPS_API_KEY from environment.",
						max_length=255,
					),
				),
				(
					"google_region",
					models.CharField(
						blank=True,
						default="CA",
						help_text="2-letter region bias for Google (e.g., CA, US).",
						max_length=2,
					),
				),
				("updated_at", models.DateTimeField(auto_now=True)),
			],
			options={
				"verbose_name_plural": "Provider settings",
			},
		),
	]
